name: CI (Checks)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Expo doctor
        run: npx expo-doctor

      - name: Lint
        run: npm run lint

      - name: Prettier check
        run: npm run fmt
