name: Repo Guardian

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_run:
    workflows: ["CI (Checks)", "Secret Scan (Gitleaks)", "CodeQL"]
    types: [completed]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: read
  issues: write

jobs:
  guard:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Run Repo Guardian
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          OWNER: ${{ github.repository_owner }}
        run: |
          node .github/scripts/repo-guardian.mjs
