name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps-template/**'
      - 'SuperPassword/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps-template/**'
      - 'SuperPassword/**'
      - '.github/workflows/**'

jobs:
  apps-template:
    name: Apps Template
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps-template

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Type Check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test:ci

  superpassword:
    name: SuperPassword
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SuperPassword

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Type Check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test:ci
